version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"  # Mapeando a porta 4200 para a porta 80 do contêiner
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
