version: '3.7'

services:
  frontend:
    build: .
    ports:
      - "80:80"
    restart: always
    environment:
      - KEYCLOAK_URL=http://localhost:8081/auth
      - KEYCLOAK_REALM=your-realm
      - KEYCLOAK_CLIENT_ID=your-client-id
